// <auto-generated />
using System;
using DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TeamManagementAPI.Migrations
{
    [DbContext(typeof(TeamDbContext))]
    partial class TeamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Model.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContractEndDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContractStartDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("Models.Model.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstablishmentِDate")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstablishmentِDate = "1390/01/01",
                            FirstColor = "قرمز",
                            Grade = "لیگ برتر",
                            Name = "تیم 1",
                            SecondColor = "سفید",
                            TeamType = "فوتبال"
                        },
                        new
                        {
                            Id = 2,
                            EstablishmentِDate = "1391/02/02",
                            FirstColor = "آبی",
                            Grade = "دسته اول",
                            Name = "تیم 2",
                            SecondColor = "سیاه",
                            TeamType = "بسکتبال"
                        },
                        new
                        {
                            Id = 3,
                            EstablishmentِDate = "1392/03/03",
                            FirstColor = "سفید",
                            Grade = "دسته دوم",
                            Name = "تیم 3",
                            SecondColor = "زرد",
                            TeamType = "والیبال"
                        },
                        new
                        {
                            Id = 4,
                            EstablishmentِDate = "1393/04/04",
                            FirstColor = "مشکلی",
                            Grade = "لیگ برتر",
                            Name = "تیم 4",
                            SecondColor = "نارنجی",
                            TeamType = "فوتبال"
                        },
                        new
                        {
                            Id = 5,
                            EstablishmentِDate = "1394/05/05",
                            FirstColor = "صورتی",
                            Grade = "دسته اول",
                            Name = "تیم 5",
                            SecondColor = "قهوه ای",
                            TeamType = "بسکتبال"
                        },
                        new
                        {
                            Id = 6,
                            EstablishmentِDate = "1395/06/06",
                            FirstColor = "خاکستری",
                            Grade = "دسته دوم",
                            Name = "تیم 6",
                            SecondColor = "بنفش",
                            TeamType = "والیبال"
                        },
                        new
                        {
                            Id = 7,
                            EstablishmentِDate = "1396/07/07",
                            FirstColor = "سفید",
                            Grade = "لیگ برتر",
                            Name = "تیم 7",
                            SecondColor = "قرمز",
                            TeamType = "هندبال"
                        },
                        new
                        {
                            Id = 8,
                            EstablishmentِDate = "1397/08/08",
                            FirstColor = "سیاه",
                            Grade = "دسته اول",
                            Name = "تیم 8",
                            SecondColor = "آبی",
                            TeamType = "بسکتبال"
                        },
                        new
                        {
                            Id = 9,
                            EstablishmentِDate = "1398/09/09",
                            FirstColor = "زرد",
                            Grade = "دسته دوم",
                            Name = "تیم 9",
                            SecondColor = "سبز",
                            TeamType = "والیبال"
                        },
                        new
                        {
                            Id = 10,
                            EstablishmentِDate = "1399/10/10",
                            FirstColor = "مشکی",
                            Grade = "لیگ برتر",
                            Name = "تیم 10",
                            SecondColor = "سبز",
                            TeamType = "فوتبال"
                        });
                });

            modelBuilder.Entity("Models.Modle.Fl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "color"
                        },
                        new
                        {
                            Id = 2,
                            Name = "teamType"
                        },
                        new
                        {
                            Id = 3,
                            Name = "grade"
                        });
                });

            modelBuilder.Entity("Models.Modle.SysList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Fl")
                        .HasColumnType("int");

                    b.Property<string>("Val")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Fl");

                    b.ToTable("SysLits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Fl = 1,
                            Val = "قرمز"
                        },
                        new
                        {
                            Id = 2,
                            Fl = 1,
                            Val = "سفید"
                        },
                        new
                        {
                            Id = 3,
                            Fl = 1,
                            Val = "آبی"
                        },
                        new
                        {
                            Id = 4,
                            Fl = 1,
                            Val = "مشکی"
                        },
                        new
                        {
                            Id = 5,
                            Fl = 1,
                            Val = "ژرد"
                        },
                        new
                        {
                            Id = 6,
                            Fl = 2,
                            Val = "فوتبال"
                        },
                        new
                        {
                            Id = 7,
                            Fl = 2,
                            Val = "بسکتبال"
                        },
                        new
                        {
                            Id = 8,
                            Fl = 2,
                            Val = "والیبال"
                        },
                        new
                        {
                            Id = 9,
                            Fl = 2,
                            Val = "هندبال"
                        },
                        new
                        {
                            Id = 10,
                            Fl = 3,
                            Val = "لیگ برتر"
                        },
                        new
                        {
                            Id = 11,
                            Fl = 3,
                            Val = "دسته یک"
                        },
                        new
                        {
                            Id = 12,
                            Fl = 3,
                            Val = "دسته دوم"
                        },
                        new
                        {
                            Id = 13,
                            Fl = 3,
                            Val = "دسته سوم"
                        });
                });

            modelBuilder.Entity("Models.Model.Player", b =>
                {
                    b.HasOne("Models.Model.Team", null)
                        .WithMany("Players")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Models.Modle.SysList", b =>
                {
                    b.HasOne("Models.Modle.Fl", null)
                        .WithMany()
                        .HasForeignKey("Fl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Models.Model.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
